sonar.organization=viceda-s
sonar.projectKey=viceda-s_SentinelOps
sonar.sources=automation
sonar.exclusions=automation/scripts/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.13
