events {}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        location / {
            proxy_pass http://api:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health/ {
            root /app;
            index index.html;
        }

        location /reports/ {
            root /app;
            autoindex off;
        }
    }
}
