global:
  resolve_timeout: 5m

route:
  receiver: webhook
  group_by: ["alertname", "job"]
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: webhook
    webhook_configs:
      - url: "http://webhook-handler:8000/alerts"
        send_resolved: true
